const DUMMY_ITEMS = [
  {
    list_item_id: 0,
    item_name: "Camera",
    category: "Fotos",
    short_description: "The must-have cameras for the best pictures",
    lists: [0, 1, 2, 3],
  },
  {
    list_item_id: 1,
    item_name: "Lens",
    category: "Fotos",
    short_description: "The perfect lens for better fotos",
    lists: [0, 1, 3],
  },
  {
    list_item_id: 2,
    item_name: "Backpack",
    category: "Fotos",
    short_description: "A packpack to transport your accesories",
    lists: [1],
  },
  {
    list_item_id: 3,
    item_name: "Tires",
    category: "Cars",
    short_description: "New tires for the winter",
    lists: [2],
  },
  {
    list_item_id: 4,
    item_name: "Car Jack",
    category: "Cars",
    short_description: "This is to lift up your car",
    lists: [2],
  },
  {
    list_item_id: 5,
    item_name: "My bike",
    category: "Bikes",
    short_description: "A bike like you've never seen",
    lists: [0, 3, 4],
  },
  {
    list_item_id: 6,
    item_name: "Red Helmet",
    category: "Bikes",
    short_description: "It will save your life",
    lists: [0, 2, 3, 5],
  },
];
